const colors = {
  light: {
    text: "#0d0d0d",
    tint: "#2DD4A0",
    background: "#ffffff",
    foreground: "#0d0d0d",
    card: "#f9f9f9",
    cardForeground: "#0d0d0d",
    primary: "#2DD4A0",
    primaryForeground: "#050505",
    secondary: "#f5f5f5",
    secondaryForeground: "#1a1a1a",
    muted: "#f5f5f5",
    mutedForeground: "#737373",
    accent: "#f5f5f5",
    accentForeground: "#1a1a1a",
    destructive: "#d93025",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#fafafa",
    tint: "#2DD4A0",
    background: "#050505",
    foreground: "#fafafa",
    card: "#0a0a0a",
    cardForeground: "#fafafa",
    primary: "#2DD4A0",
    primaryForeground: "#050505",
    secondary: "#1a1a1a",
    secondaryForeground: "#fafafa",
    muted: "#1a1a1a",
    mutedForeground: "#999999",
    accent: "#1a1a1a",
    accentForeground: "#fafafa",
    destructive: "#c0392b",
    destructiveForeground: "#fafafa",
    border: "#1f1f1f",
    input: "#1f1f1f",
  },
  radius: 4,
};

export default colors;
