kind = "mobile"
previewPath = "/mobile/"
title = "Sever Mobile"
version = "1.0.0"
id = "artifacts/sever-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 22973

[services.development]
run = "pnpm --filter @workspace/sever-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sever-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/sever-mobile", "run", "serve" ]

[services.env]
PORT = "22973"
BASE_PATH = "/mobile/"
